@startuml

|client| Клиент
|marketing| Маркетинговый отдел
|operation| Операционный отдел
|composition| Склад
|client|
start
:Выбор услуги;
|marketing|
:Анализ запроса;
|marketing|
:Создание запроса
на оценку услуг;
|operation|
:Оценка стоимости
услуг;
|operation|
:Формирование
счета на оплату;
|client|
:Подтверждение
готовности оплатить;
|operation|
:Забрать посылку 
у Клиента;
|operation|
:Отправить на склад;
|composition|
:Подготовка к отгрузке
(процедуры внутреннего
офрмления, в т.ч. QR);
|composition|
:Отгрузка;
|operation|
:Доставка Клиенту;
|client|
:Приемка Заказа;
|client|
:Оплата услуг;
stop
@enduml